In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler , Normalizer
import numpy as np
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
df=pd.read_csv(r'D:/output_3.csv')
pd.set_option('display.max_columns', None)
df.head()

,fever,bodyPain,age,runnyNose,diffBreath,infectionProb,temp,drycough,diarrhoea,nasal_congestion,contact
0,99.254765,1,85,1,1,1,0,0,0,1,0
1,99.254765,1,85,1,1,1,1,0,1,1,1
2,99.254765,1,85,1,1,1,0,1,0,1,0
3,99.254765,1,85,1,1,1,1,0,0,1,0
4,99.254765,1,85,1,1,1,2,1,0,0,1

In [2]:
df.describe()

,fever,bodyPain,age,runnyNose,diffBreath,infectionProb,temp,drycough,diarrhoea,nasal_congestion,contact
count,2.690012e+06,2.690012e+06,2.690012e+06,2.690012e+06,2.690012e+06,2.690012e+06,2.690012e+06,2.690012e+06,2.690012e+06,2.690012e+06,2.690012e+06
mean,1.000023e+02,4.967517e-01,5.002401e+01,4.902677e-01,5.032483e-01,5.093278e-01,1.016451e+00,5.082557e-01,5.050966e-01,5.034215e-01,9.969279e-01
std,1.129312e+00,4.999895e-01,2.904396e+01,4.999054e-01,4.999895e-01,4.999131e-01,8.211187e-01,4.999319e-01,4.999741e-01,4.999884e-01,8.154109e-01
min,9.800030e+01,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,9.903878e+01,0.000000e+00,2.500000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,9.999305e+01,0.000000e+00,5.000000e+01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
75%,1.009617e+02,1.000000e+00,7.500000e+01,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00
max,1.019923e+02,1.000000e+00,1.000000e+02,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00

In [3]:
df.loc[df['fever']<99,'fever']=0
df.loc[df['fever']>=99,'fever']=1
df['fever'].unique()

array([1., 0.])

In [4]:
data=df.copy()
data.drop('age',inplace=True,axis=1)

In [5]:
data.drop('temp',axis=1,inplace=True)
data.head()

,fever,bodyPain,runnyNose,diffBreath,infectionProb,drycough,diarrhoea,nasal_congestion,contact
0,1.0,1,1,1,1,0,0,1,0
1,1.0,1,1,1,1,0,1,1,1
2,1.0,1,1,1,1,1,0,1,0
3,1.0,1,1,1,1,0,0,1,0
4,1.0,1,1,1,1,1,0,0,1

In [6]:
data['sum1']=0
for i in data.columns:
    data['sum1']+=data[i]
data['sum1'].mean()
print(data['sum1'])

0          12.0
1          16.0
2          14.0
3          12.0
4          14.0
           ...
2690007    10.0
2690008    10.0
2690009    10.0
2690010     8.0
2690011     6.0
Name: sum1, Length: 2690012, dtype: float64

In [7]:
data.loc[data['sum1']<12,'sum1']=0
data.loc[data['sum1']>=12,'sum1']=1

In [8]:
data['sum1']

0          1.0
1          1.0
2          1.0
3          1.0
4          1.0
          ...
2690007    0.0
2690008    0.0
2690009    0.0
2690010    0.0
2690011    0.0
Name: sum1, Length: 2690012, dtype: float64

In [9]:
data['infectionProb']*=2
data['infectionProb'].unique()

array([2, 0], dtype=int64)

In [10]:
data['finalProb'] = data['infectionProb'] + data['sum1']

In [11]:
data['finalProb'].unique()

array([3., 2., 0., 1.])

In [14]:
df['infectionProb']=data['finalProb']
df

,fever,bodyPain,age,runnyNose,diffBreath,infectionProb,temp,drycough,diarrhoea,nasal_congestion,contact
0,1.0,1,85,1,1,3.0,0,0,0,1,0
1,1.0,1,85,1,1,3.0,1,0,1,1,1
2,1.0,1,85,1,1,3.0,0,1,0,1,0
3,1.0,1,85,1,1,3.0,1,0,0,1,0
4,1.0,1,85,1,1,3.0,2,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
2690007,1.0,0,15,1,0,0.0,2,1,0,1,1
2690008,1.0,0,15,1,0,0.0,0,1,0,1,1
2690009,1.0,0,15,1,0,0.0,1,1,1,1,0
2690010,1.0,0,15,1,0,0.0,2,1,1,0,0
2690011,1.0,0,15,1,0,0.0,0,0,0,0,1

In [15]:
scaled_features = df.copy()
col_names = ['fever', 'age']
features = scaled_features[col_names]
scaler = StandardScaler().fit(features.values)
features = scaler.transform(features.values)
scaled_features[col_names] = features
print(scaled_features)

            fever  bodyPain       age  runnyNose  diffBreath  infectionProb  \
0        0.557758         1  1.204243          1           1            3.0
1        0.557758         1  1.204243          1           1            3.0
2        0.557758         1  1.204243          1           1            3.0
3        0.557758         1  1.204243          1           1            3.0
4        0.557758         1  1.204243          1           1            3.0
...           ...       ...       ...        ...         ...            ...
2690007  0.557758         0 -1.205897          1           0            0.0
2690008  0.557758         0 -1.205897          1           0            0.0
2690009  0.557758         0 -1.205897          1           0            0.0
2690010  0.557758         0 -1.205897          1           0            0.0
2690011  0.557758         0 -1.205897          1           0            0.0

         temp  drycough  diarrhoea  nasal_congestion  contact
0           0         0          0                 1        0
1           1         0          1                 1        1
2           0         1          0                 1        0
3           1         0          0                 1        0
4           2         1          0                 0        1
...       ...       ...        ...               ...      ...
2690007     2         1          0                 1        1
2690008     0         1          0                 1        1
2690009     1         1          1                 1        0
2690010     2         1          1                 0        0
2690011     0         0          0                 0        1

[2690012 rows x 11 columns]

In [16]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2  #target column i.e price range
#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2, k=7)
x=df.drop('infectionProb',axis=1)
y=df['infectionProb']
fit = bestfeatures.fit(x,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x.columns)
#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(10,'Score'))

              Specs          Score
9           contact  331085.411408
1          bodyPain  112244.675609
3         runnyNose  104355.158698
6          drycough   90960.372480
7         diarrhoea   78397.151629
4        diffBreath   77625.766019
8  nasal_congestion   69413.349848
0             fever   32002.383146
2               age    2165.722970
5              temp      68.516634

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.3)
model=RandomForestClassifier(n_estimators=100, max_depth=None, min_samples_split=2, min_samples_leaf=1)
model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred=model.predict(x_test)

In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7916648300671957

In [20]:
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import f1_score
print(confusion_matrix(y_test,y_pred))
temp=classification_report(y_test,y_pred)
print(temp)

[[499858      0  78333  51880]
 [     0 228767      0  65122]
 [ 82100      0 331797      0]
 [ 50638  64224      0 430290]]
              precision    recall  f1-score   support

         0.0       0.79      0.79      0.79    630071
         1.0       0.78      0.78      0.78    293889
         2.0       0.81      0.80      0.81    413897
         3.0       0.79      0.79      0.79    545152

    accuracy                           0.79   1883009
   macro avg       0.79      0.79      0.79   1883009
weighted avg       0.79      0.79      0.79   1883009

In [25]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 500, num = 5)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(10, 100, num = 6)]
max_depth.append(None)
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2]
bootstrap = [True, False]
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 28, 46, 64, 82, 100, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2], 'bootstrap': [True, False]}

In [26]:
rf = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 2, verbose=2, random_state=42, n_jobs = -1)

In [ ]:
rf_random.fit(x_train,y_train)

Fitting 2 folds for each of 100 candidates, totalling 200 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.